name: CI GitHub Actions

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
    - cron:  '1 0 * * 1'    # * is a special character in YAML, therefore this string needs to be quoted

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 5.0.100-rc.2.20479.15

    - name: Build
      run: dotnet build -c Release

    - name: Run tests
      run: dotnet test -c Release --no-build
