name: CI GitHub Actions

on:
  push:
  pull_request:
  schedule:
    - cron:  '1 0 * * 1'    # * is a special character in YAML, therefore this string needs to be quoted

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      ARTIFACT_DIR: ./Artifacts

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.403

    - name: Append -ci-${{ env.BUILD_VERSION }} to version
      if: matrix.os == 'ubuntu-latest'
      shell: pwsh
      run: |
        $input_path = "Directory.Build.props"
        $regex = "(?<=<Version>).*(?=</Version>)"
        (Get-Content $input_path) -Replace $regex, '$0-ci-${{ github.run_number }}' | Out-File $input_path

    - name: Build
      run: dotnet build -c Release

    - name: Run tests
      run: dotnet test -c Release --no-build

    - name: Pack
      if: matrix.os == 'ubuntu-latest'
      run: |
        dotnet pack -c Release --no-build src/SheepTools/SheepTools.csproj --include-symbols -o ${{ env.ARTIFACT_DIR }}
        dotnet pack -c Release --no-build src/SheepTools.Moq/SheepTools.Moq.csproj --include-symbols -o ${{ env.ARTIFACT_DIR }}
        dotnet pack -c Release --no-build src/SheepTools.XUnit/SheepTools.XUnit.csproj --include-symbols -o ${{ env.ARTIFACT_DIR }}

    - name: Upload Artifact
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: SheepTools-ci-artifact
        path: ${{ env.ARTIFACT_DIR }}/*.nupkg
        if-no-files-found: error
